### ISSUE TITLE
Compile to support ES5

### ISSUE THREAD

**Issue by ovangle** [darrylhodgins/typescript-memoize#1]
Sorry, posted this without an actual description of the problem.

Could this library with UMD modules? I'm trying to load the decorator using systemjs but it's giving me a traceur error, because of the `export function` in `dist/memoize-decorator.js`.

In an ideal world browsers would natively support ES6 modules by now, but...

It should be as simple as setting `module: UMD` in your `tsconfig.json` and republishing the package.

**Comment by darrylhodgins** [comment]
Seems reasonable, though I would have expected most projects would be using some kind of build step such as Webpack to resolve modules.

**Comment by ovangle** [comment]
It was mainly for my unit tests (which I run with systemJS and didn't transpile because of the overhead) that I thought it was a good idea. I had to switch to transpiled modules anyway when I found out that `ng-bootstrap` requires ES6 imports.

So just close this and forget about it.

**Comment by darrylhodgins** [comment]
@ovangle, I've added my unit tests & pushed `v1.0.0-alpha.1` to NPM, in addition to changing the module to `umd` (which I _think_ is actually a pretty good idea).  I haven't made any other changes to the package, but please let me know if the `module` change breaks your build.

For now, I'll close this issue as complete.
