### ISSUE TITLE
@MemoizeExpiring isn't available on ^1.0.0-alpha.4

### ISSUE THREAD

**Issue by ziv-kalderon** [darrylhodgins/typescript-memoize#22]
Hey guys,
First of all, this decorator is a-w-e-s-o-m-e 
Second, it seems like @MemoizeExpiring isn't available on the latest package in npm...
Can I help somehow with it?

Thanks

**Comment by darrylhodgins** [comment]
It looks like I've forgotten to publish it.  I'll do that…

**Comment by ziv-kalderon** [comment]
Thank you for the quick response:)

**Comment by darrylhodgins** [comment]
@ziv-kalderon, the response may have been quick, but it's going to be a short while before I get back to my computer to publish it.  Feel free to remind me if I forget 🙂

**Comment by ziv-kalderon** [comment]
I will:) thank you

**Comment by ziv-kalderon** [comment]
Just a friendly reminder...

**Comment by darrylhodgins** [comment]
@ziv-kalderon, I've bumped it to a non-alpha `1.0.0` and published.  Let me know if you have any issues!
