### ISSUE TITLE
Document the unit of time used by the expiring option

### ISSUE THREAD

**Issue by sambs** [darrylhodgins/typescript-memoize#36]
It's not clear from the readme what unit of time the expiry option uses. Seconds? Milliseconds?

**Comment by darrylhodgins** [comment]
Good point.  In the meantime, it's [milliseconds](https://github.com/darrylhodgins/typescript-memoize/blob/master/test/specs/memoize-decorator.spec.ts#L316).

**Comment by sambs** [comment]
Great, thanks for the quick response!
